resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: buildandPush
  displayName: Build and Push image
  jobs:  
  - job: buildandPush
    displayName: Build and Push image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-registry-connection'
        repository: 'chandlermcfly/node'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: deployAKS
  displayName: Deploy image to AKS
  jobs:  
  - job: deployAKS
    displayName: Deploy image to AKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'specific'
        project: 'c302241c-40ab-4f58-ae6c-b736a11ea92c'
        definition: '3'
        specificBuildWithTriggering: true
        buildVersionToDownload: 'latest'
        artifactName: 'manifests'
        itemPattern: 'manisfests/*.yml'
        targetPath: '$(System.ArtifactsDirectory)'
