resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: buildandPush
  displayName: Build and Push image
  jobs:  
  - job: buildandPush
    displayName: Build and Push image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-registry-connection'
        repository: 'chandlermcfly/node'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(tag)'
- stage: deployAKS
  displayName: Deploy image to AKS
  jobs:  
  - job: deployAKS
    displayName: Deploy image to AKS
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: '$(System.ArtifactsDirectory)'
        artifact: 'manifests'
        publishLocation: 'pipeline'
    - task: DownloadPipelineArtifact@2
      inputs:
        buildType: 'current'
        artifactName: 'manifests'
        itemPattern: '**/*.yaml'
        targetPath: '$(System.ArtifactsDirectory)'
