trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: buildandPush
  displayName: Build and Push image
  jobs:  
  - job: Build
    displayName: Build and Push image
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'dockerhub-registry-connection'
        repository: 'chandlermcfly/node'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'